name: 'Test encoding github context'
description: 'Test encoding github context'
branding:
  icon: lock
  color: purple
inputs:
  github_context:
    description: 'internal (do not set): the "github" context object in json'
    required: true
    default: ${{ toJSON(github) }}
runs:
  using: 'composite'
  steps:
    - name: compose arguments
      id: compose-args
      shell: bash
      run: |
        echo ${{ inputs.github_context }} > github_context.json
        encoded_github="$(cat github_context.json | base64 -w 0)"
        rm github_context.json
        echo "Encoded github_context"
        echo "${encoded_github}"
